# Generated by Django 5.2.8 on 2025-11-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fin', models.CharField(max_length=5)),
                ('ubicacion', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Usuario',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='UsuarioInsignia',
            fields=[
                ('id_usuario_insignia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_obtencion', models.DateField()),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
            options={
                'verbose_name': 'Insignia Obtenida',
                'verbose_name_plural': 'Insignias de Usuarios',
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
