# Generated by Django 5.2.8 on 2025-11-23 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=1000)),
                ('estado_notificacion', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario', verbose_name='Usuario Destino')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
