# Generated by Django 5.2.8 on 2025-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_habilidad', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id_insignia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_insignia', models.CharField(max_length=100)),
                ('descripcion_insignia', models.CharField(max_length=500)),
                ('requisitos', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=100, unique=True, verbose_name='Correo Institucional')),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
                ('estado_cuenta', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
            },
        ),
    ]
