# Generated by Django 5.2.8 on 2025-11-23 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado_creacion', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.habilidad', verbose_name='Habilidad Relacionada')),
            ],
            options={
                'verbose_name': 'Intercambio de Habilidad',
                'verbose_name_plural': 'Intercambios de Habilidades',
            },
        ),
        migrations.CreateModel(
            name='UsuarioIntercambio',
            fields=[
                ('id_usuario_intercambio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('inter_buscado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buscado_en_transacciones', to='intercambio.intercambio', verbose_name='Intercambio Buscado')),
                ('inter_ofrecido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofrecido_en_transacciones', to='intercambio.intercambio', verbose_name='Intercambio Ofrecido')),
                ('intercambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_relacionadas', to='intercambio.intercambio', verbose_name='Intercambio Principal')),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_recibidos', to='accounts.usuario', verbose_name='Receptor')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_solicitados', to='accounts.usuario', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Transacción de Usuario-Intercambio',
                'verbose_name_plural': 'Transacciones de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion_reporte', models.TextField(verbose_name='Descripción')),
                ('estado_reporte', models.CharField(max_length=20)),
                ('justificacion_admin', models.CharField(max_length=1000)),
                ('usuario_intercambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambio.usuariointercambio', verbose_name='Transacción Reportada')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
